package com.shutdowntracker.projectworker.handoff;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationRequest;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationResponse;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactSummary;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(WorkerProjectExportArtifactController.class)
class WorkerProjectExportArtifactControllerTests {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private WorkerProjectExportArtifactHandoffService handoffService;

    @Test
    void returnsGeneratedExportArtifactSummary() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        when(handoffService.generateArtifact(any(ProjectExportArtifactGenerationRequest.class)))
                .thenReturn(new ProjectExportArtifactGenerationResponse(
                        exportBatchId,
                        projectId,
                        "file:///synthetic/export-artifacts/export.mspdi.xml",
                        "synthetic-sha256",
                        new ProjectExportArtifactSummary(
                                "export.mspdi.xml",
                                "mspdi_xml",
                                1,
                                1,
                                512,
                                "synthetic-sha256",
                                List.of("MSPDI/XML artifact only; no schedule calculations or Microsoft Project write-back were run.")
                        ),
                        "MSPDI/XML artifact generated by project worker. No Microsoft Project write-back was run."
                ));

        String body = """
                {
                  "exportBatchId": "%s",
                  "projectId": "%s",
                  "outputPath": ".shutdown-tracker/export-artifacts/%s.mspdi.xml",
                  "artifactRequest": {
                    "projectName": "Synthetic Export Preview",
                    "tasks": [
                      {
                        "importedTaskId": "synthetic-task-a1",
                        "microsoftProjectTaskUid": "101",
                        "microsoftProjectTaskId": "1",
                        "taskName": "Synthetic Task A1",
                        "leafTask": true,
                        "fieldValues": [
                          {
                            "field": "PERCENT_COMPLETE",
                            "newValue": "75"
                          }
                        ]
                      }
                    ]
                  }
                }
                """.formatted(exportBatchId, projectId, exportBatchId);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.exportBatchId").value(exportBatchId.toString()))
                .andExpect(jsonPath("$.projectId").value(projectId.toString()))
                .andExpect(jsonPath("$.artifactSummary.artifactFormat").value("mspdi_xml"))
                .andExpect(jsonPath("$.message").value("MSPDI/XML artifact generated by project worker. No Microsoft Project write-back was run."));

        verify(handoffService).generateArtifact(any(ProjectExportArtifactGenerationRequest.class));
    }
}
