package com.shutdowntracker.projectworker.handoff;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationRequest;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationResponse;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactSummary;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

@WebMvcTest(WorkerProjectExportArtifactController.class)
class WorkerProjectExportArtifactControllerTests {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private WorkerProjectExportArtifactHandoffService handoffService;

    @Test
    void returnsGeneratedExportArtifactSummary() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        when(handoffService.generateArtifact(any(ProjectExportArtifactGenerationRequest.class)))
                .thenReturn(new ProjectExportArtifactGenerationResponse(
                        exportBatchId,
                        projectId,
                        "file:///synthetic/export-artifacts/export.mspdi.xml",
                        "synthetic-sha256",
                        new ProjectExportArtifactSummary(
                                "export.mspdi.xml",
                                "mspdi_xml",
                                1,
                                1,
                                512,
                                "synthetic-sha256",
                                List.of("MSPDI/XML artifact only; no schedule calculations or Microsoft Project write-back were run.")
                        ),
                        "MSPDI/XML artifact generated by project worker. No Microsoft Project write-back was run."
                ));

        String body = """
                {
                  "exportBatchId": "%s",
                  "projectId": "%s",
                  "outputPath": ".shutdown-tracker/export-artifacts/%s.mspdi.xml",
                  "artifactRequest": {
                    "projectName": "Synthetic Export Preview",
                    "tasks": [
                      {
                        "importedTaskId": "synthetic-task-a1",
                        "microsoftProjectTaskUid": "101",
                        "microsoftProjectTaskId": "1",
                        "taskName": "Synthetic Task A1",
                        "leafTask": true,
                        "fieldValues": [
                          {
                            "field": "PERCENT_COMPLETE",
                            "newValue": "75"
                          }
                        ]
                      }
                    ]
                  }
                }
                """.formatted(exportBatchId, projectId, exportBatchId);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.exportBatchId").value(exportBatchId.toString()))
                .andExpect(jsonPath("$.projectId").value(projectId.toString()))
                .andExpect(jsonPath("$.artifactSummary.artifactFormat").value("mspdi_xml"))
                .andExpect(jsonPath("$.message").value("MSPDI/XML artifact generated by project worker. No Microsoft Project write-back was run."));

        verify(handoffService).generateArtifact(any(ProjectExportArtifactGenerationRequest.class));
    }

    @Test
    void rejectsPhysicalPercentCompleteBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String body = requestBody(exportBatchId, projectId, """
                {
                  "field": "PHYSICAL_PERCENT_COMPLETE",
                  "newValue": "50"
                }
                """);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsDuplicateTaskFieldCandidatesBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String body = requestBody(exportBatchId, projectId, """
                {
                  "field": "PERCENT_COMPLETE",
                  "newValue": "75"
                },
                {
                  "field": "PERCENT_COMPLETE",
                  "newValue": "75"
                }
                """);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsUnknownScheduleAuthorityPropertiesBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String body = requestBody(exportBatchId, projectId, """
                {
                  "field": "PERCENT_COMPLETE",
                  "newValue": "75"
                }
                """).replace(
                "\"leafTask\": true,",
                "\"leafTask\": true,\n                        \"plannedStart\": \"2026-01-05T07:00:00Z\","
        );

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsNumericEnumAliasesBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String body = requestBody(exportBatchId, projectId, """
                {
                  "field": 0,
                  "newValue": "75"
                }
                """);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsDuplicateJsonPropertiesBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String body = requestBody(exportBatchId, projectId, """
                {
                  "field": "PERCENT_COMPLETE",
                  "field": "ACTUAL_START",
                  "newValue": "75"
                }
                """);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsSummaryMissingAndNonCanonicalTaskIdentityBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String validBody = requestBody(exportBatchId, projectId, """
                {
                  "field": "PERCENT_COMPLETE",
                  "newValue": "75"
                }
                """);

        List<String> invalidBodies = List.of(
                validBody.replace("\"leafTask\": true", "\"leafTask\": false"),
                validBody.replace("\"microsoftProjectTaskUid\": \"101\",", ""),
                validBody.replace("\"microsoftProjectTaskUid\": \"101\"", "\"microsoftProjectTaskUid\": \"01\""),
                validBody.replace("\"microsoftProjectTaskId\": \"1\"", "\"microsoftProjectTaskId\": \"+1\"")
        );

        for (String body : invalidBodies) {
            mockMvc.perform(post("/worker/project-export/generate-artifact")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content(body))
                    .andExpect(status().isBadRequest());
        }

        verifyNoInteractions(handoffService);
    }

    @Test
    void rejectsNonzeroFractionalActualBeforeCallingHandoffService() throws Exception {
        UUID projectId = UUID.randomUUID();
        UUID exportBatchId = UUID.randomUUID();
        String body = requestBody(exportBatchId, projectId, """
                {
                  "field": "ACTUAL_START",
                  "newValue": "2026-01-05T16:00:00.001+08:00"
                }
                """);

        mockMvc.perform(post("/worker/project-export/generate-artifact")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest());

        verifyNoInteractions(handoffService);
    }

    private String requestBody(UUID exportBatchId, UUID projectId, String fieldValues) {
        return """
                {
                  "exportBatchId": "%s",
                  "projectId": "%s",
                  "outputPath": ".shutdown-tracker/export-artifacts/%s.mspdi.xml",
                  "artifactRequest": {
                    "projectName": "Synthetic Export Preview",
                    "tasks": [
                      {
                        "importedTaskId": "synthetic-task-a1",
                        "microsoftProjectTaskUid": "101",
                        "microsoftProjectTaskId": "1",
                        "taskName": "Synthetic Task A1",
                        "leafTask": true,
                        "fieldValues": [
                          %s
                        ]
                      }
                    ]
                  }
                }
                """.formatted(exportBatchId, projectId, exportBatchId, fieldValues);
    }
}
