package com.shutdowntracker.projectworker.handoff;

import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationRequest;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationResponse;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactSummary;
import com.shutdowntracker.projectworker.exporter.ProjectExportArtifactService;
import com.shutdowntracker.projectworker.storage.WorkerStoragePathResolver;
import com.shutdowntracker.projectworker.storage.WorkerStorageProperties;
import java.nio.file.Path;
import java.util.Objects;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class WorkerProjectExportArtifactHandoffService {

    private static final String MESSAGE =
            "MSPDI/XML artifact generated by project worker. No Microsoft Project write-back was run.";

    private final ProjectExportArtifactService exportArtifactService;
    private final WorkerStoragePathResolver storagePathResolver;

    @Autowired
    public WorkerProjectExportArtifactHandoffService(
            ProjectExportArtifactService exportArtifactService,
            WorkerStoragePathResolver storagePathResolver
    ) {
        this.exportArtifactService = exportArtifactService;
        this.storagePathResolver = storagePathResolver;
    }

    /** Package-private compatibility constructor for isolated unit tests only. */
    WorkerProjectExportArtifactHandoffService(ProjectExportArtifactService exportArtifactService) {
        this(
                exportArtifactService,
                new WorkerStoragePathResolver(new WorkerStorageProperties(
                        Path.of(System.getProperty("java.io.tmpdir")),
                        Path.of(System.getProperty("java.io.tmpdir"))
                ))
        );
    }

    public ProjectExportArtifactGenerationResponse generateArtifact(ProjectExportArtifactGenerationRequest request) {
        Objects.requireNonNull(request, "request is required.");
        Path outputPath = storagePathResolver.resolveExportArtifactOutput(request.outputPath());
        ProjectExportArtifactSummary summary = exportArtifactService.generate(request.artifactRequest(), outputPath);
        return new ProjectExportArtifactGenerationResponse(
                request.exportBatchId(),
                request.projectId(),
                outputPath.toUri().toString(),
                summary.sha256(),
                summary,
                MESSAGE
        );
    }
}
