package com.shutdowntracker.projectworker.handoff;

import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationRequest;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactGenerationResponse;
import com.shutdowntracker.projectexport.contract.ProjectExportArtifactSummary;
import com.shutdowntracker.projectworker.exporter.ProjectExportArtifactService;
import com.shutdowntracker.projectworker.storage.WorkerStoragePathResolver;
import com.shutdowntracker.projectworker.storage.WorkerStorageProperties;
import java.nio.file.Path;
import java.util.Objects;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class WorkerProjectExportArtifactHandoffService {

    private static final String MESSAGE =
            "MSPDI/XML candidate schedule generated by project worker from the accepted source. "
                    + "No Microsoft Project write-back was run.";

    private final ProjectExportArtifactService exportArtifactService;
    private final WorkerStoragePathResolver storagePathResolver;

    @Autowired
    public WorkerProjectExportArtifactHandoffService(
            ProjectExportArtifactService exportArtifactService,
            WorkerStoragePathResolver storagePathResolver
    ) {
        this.exportArtifactService = exportArtifactService;
        this.storagePathResolver = storagePathResolver;
    }

    /** Package-private compatibility constructor for isolated unit tests only. */
    WorkerProjectExportArtifactHandoffService(ProjectExportArtifactService exportArtifactService) {
        this(
                exportArtifactService,
                Path.of(System.getProperty("java.io.tmpdir")),
                Path.of(System.getProperty("java.io.tmpdir"))
        );
    }

    /**
     * Package-private constructor for tests that read a committed fixture as the accepted source,
     * which lives outside the temporary directory the constructor above confines to.
     */
    WorkerProjectExportArtifactHandoffService(
            ProjectExportArtifactService exportArtifactService,
            Path sourceFileRoot,
            Path exportArtifactRoot
    ) {
        this(
                exportArtifactService,
                new WorkerStoragePathResolver(new WorkerStorageProperties(sourceFileRoot, exportArtifactRoot))
        );
    }

    public ProjectExportArtifactGenerationResponse generateArtifact(ProjectExportArtifactGenerationRequest request) {
        Objects.requireNonNull(request, "request is required.");
        Path outputPath = storagePathResolver.resolveExportArtifactOutput(request.outputPath());
        // The same confinement the import path uses: the accepted source must resolve under the
        // configured source-file root, so a storage URI cannot reach elsewhere on disk.
        Path sourcePath = storagePathResolver.resolveSourceFile(request.artifactRequest().source().storageUri());
        ProjectExportArtifactSummary summary =
                exportArtifactService.generate(request.artifactRequest(), sourcePath, outputPath);
        return new ProjectExportArtifactGenerationResponse(
                request.exportBatchId(),
                request.projectId(),
                outputPath.toUri().toString(),
                summary.sha256(),
                summary,
                MESSAGE
        );
    }
}
