spring:
  application:
    name: shutdown-tracker-api
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

shutdown-tracker:
  source-file-validation:
    max-size-bytes: 52428800
